InvalidID-FAQ-Update.md
GSA-TTS/identity-idva-docs pull request #157
Opened 2024-02-07 21:06 UTC by ptolleyedc

2024-02-07 21:10 UTC, ptolleyedc commented
I have not tested this locally, Nathan is taking a look at doing that. This is to move forward to see how the page builds so we are not entirely blocked

2024-02-12 15:55 UTC, astrogeco requested changes

2024-02-12 15:55 UTC, astrogeco commented on _pages/faqs.md
> +    <img src="https://feedback.gsa.gov/CP/Graphic.php?IM=IM_ddjGgMJHuJ5smxM" style="width: 65%;"><br><br>
Upload picture directly to repository and replace `src`

Add empty `alt` tag (see home page for example)

2024-02-12 15:55 UTC, astrogeco commented on _pages/faqs.md
> +    <img src="https://feedback.gsa.gov/CP/Graphic.php?IM=IM_cM91zAksWWMyOdU"><br><br>
Upload picture directly to repository and replace `src`

Add empty `alt` tag

2024-02-12 20:22 UTC, astrogeco requested changes

2024-02-12 20:22 UTC, astrogeco commented on _pages/faqs.md
> -**Please use the same ID for all pictures.** Note that a worn or damaged picture may prevent the identity verification process from working.
Need to include this statement somewhere

2024-02-12 20:44 UTC, astrogeco approved these changes

2024-02-12 20:45 UTC, merged